spring:
  application:
    name: gameet

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_MAIL_USERNAME}
    password: ${JAVA_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}

aws:
  ses:
    access_key: ${AWS_SES_ACCESS_KEY}
    secret_key: ${AWS_SES_SECRET_KEY}
    region: ${AWS_SES_REGION}
    from_email_address: ${AWS_SES_FROM_EMAIL_ADDRESS}

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web: DEBUG

discord:
  webhook:
    websocket-uri: ${WEBSOCKET_SESSION_ISSUE_CHANNEL}
