name: Docker Build and Push and EC2 Deployment
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Create serverKey.json
        run: echo "${{ secrets.SERVER_KEY_JSON }}" > src/main/resources/serverKey.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Upload .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env"
          target: "/home/ubuntu/"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gameet-app:${{ github.sha }} .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gameet-app:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/gameet-app:${{ github.sha }}
            docker stop gameet-container || true
            docker rm gameet-container || true
            
            docker image rm $IMAGE_NAME || true
            docker pull $IMAGE_NAME
            
            docker run -d \
              --name gameet-container \
              --network gameet-net \
              --env-file /home/ubuntu/.env \
              -e REDIS_HOST=redis-gameet \
              -e TZ=Asia/Seoul \
              -p 8080:8080 \
              $IMAGE_NAME